# Use a config map to inject some files into the container.
# Don't use this method in production.  You should build an actual container, or use real volumes.

#  https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1/
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-files
data:
  "index.php": "<?php phpinfo();"

