# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: php:7.4.33-apache-bullseye
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html
            name: my-app-files
      volumes:
        - name: my-app-files
          # Use a config map to inject some files into the container.
          # Don't use this method in production.  You should build an actual container, or use real volumes.
          configMap:
            name: my-app-files