# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-b

resources:
  - namespace.yaml
  - ingress.yaml
  - ../../bases/production
