# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
# https://blog.kublr.com/setting-up-mysql-replication-clusters-in-kubernetes-ab7cbac113a5
# https://www.serverlab.ca/tutorials/containers/kubernetes/how-to-deploy-mysql-server-5-7-to-kubernetes/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql-example

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

